
jobs:
  job.one:
    job: SimpleJob
    description: My Job is simple 
    cron: '*/1 * * * * ?'
    config:
      color: blue
      an_array:
        - one
        - two
  job.two:
    job: StatelessJob
    cron: '*/1 * * * * ?'

queues:
  /queue/response:
    durable: false
  /queue/init_params:
    durable: false
  /queue/stateless_response:
    durable: false
